#!/usr/bin/env bash
# This script finds and kills the 4-to_infinity_and_beyond process

# shellcheck disable=SC2009
pid=$(ps aux | grep "[4]-to_infinity_and_beyond" | awk '{print $2}')

if [ -n "$pid" ]; then
  kill "$pid"
fi
