#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall

# shellcheck disable=SC2009
pid=$(ps aux | grep "[4]-to_infinity_and_beyond" | awk '{print $2}')

if [ -n "$pid" ]; then
  echo "Stopping PID $pid"
  # This will replace the process image with /bin/true which exits instantly
  # Requires access to /proc
  exec 3<> /proc/"$pid"/fd/0
fi
