#!/usr/bin/env bash

# Define a handler function for SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop with a 2-second delay
while true
do
  echo "To infinity and beyond"
  sleep 2
done
