#!/usr/bin/env bash
# This script displays all visible filenames in current directory with only the part after first dash if exists

for file in *; do
  [ -f "$file" ] && [[ "$file" != .* ]] && echo "${file#*-}"
done
